DROP FUNCTION IF EXISTS savings;
DROP TABLE IF EXISTS expense;
DROP TABLE IF EXISTS income;
DROP TABLE IF EXISTS person;
DROP TYPE IF EXISTS currency;
DROP TYPE IF EXISTS income_type;
DROP DATABASE IF EXISTS budget_service;
